### ISSUE TITLE
make introprog.PixelWindow handle Delet key in clear text

### ISSUE THREAD

**Issue by bjornregnell** [lunduniversity/introprog-scalalib#1] opened 2018-07-04 12:34 UTC
Delete key is now a special utf charcter displayed as  or \utf(007F). Make lastKey be "Delete"

**Comment by elliotbrack** [comment] 2019-11-20 17:27
This also goes for the arrow keys, enter key, tab, and so on on OS X. Is that out of scope for the project? I imagine you'd want some sort of Map[String, String] for all the special characters, or handle all the special cases by their keycode.

The root cause is Java special handling on OS X to make ⌘ et al display correctly, so I imagine you could extract the lookup table from that.

**Closed** 2020-11-08 16:45 UTC
Labels: enhancement, good first issue, help wanted
